from src.modules.get_all_products_by_restaurant.app.get_all_product_by_restaurant_viewmodel import GetAllProductsByRestaurantViewmodel
from src.shared.infra.repositories.product_repository_mock import ProductRepositoryMock
from src.shared.domain.entities.product import Product


class Test_GetAllProductsByRestaurantViewmodel:
    def test_get_all_products_by_restaurant_viewmodel(self):
        repo = ProductRepositoryMock()
        all_products = repo.products
        viewmodel = GetAllProductsByRestaurantViewmodel(all_products=all_products)
        
        expected = {
        'all_products':[
            {
                'available':True,
                'price':14.0,
                'name':'Lanche Mortadela',
                'description':'Mortadela',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':0,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':16.0,
                'name':'X-Salada',
                'description':'Hamburguer/Mussarela/Maionese/Alface/Tomate',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':1,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'X-Burguer',
                'description':'Hamburguer/Mussarela/Maionese',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':2,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':18.0,
                'name':'X-Bacon',
                'description':'Hamburguer/Bacon/Mussarela/Maionese/Alface/Tomate',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':3,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':15.0,
                'name':'X-Egg',
                'description':'Hamburguer/Ovo/Mussarela/Maionese/Alface/Tomate',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':4,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':18.0,
                'name':'X-Calabresa',
                'description':'Calabresa/Mussarela/Alface/Tomate',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':5,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':18.0,
                'name':'X-Frango',
                'description':'Filé de Frango/Mussarela/Maionese/Alface/Tomate',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':6,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':16.0,
                'name':'Americano',
                'description':'Presunto/Ovo/Mussarela/Maionese/Alface/Tomate/Orégano',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':7,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':12.0,
                'name':'Misto Quente',
                'description':'Presunto/Mussarela/Orégano',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':8,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':13.0,
                'name':'Bauru',
                'description':'Presunto/Mussarela/Tomate/Orégano',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':9,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':18.0,
                'name':'Churrasco',
                'description':'Contra Filé',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':10,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':21.0,
                'name':'Ch. c/ Queijo',
                'description':'Contra Filé/Mussarela',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':11,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':23.0,
                'name':'Ch. c/ Vinag.',
                'description':'Contra Filé/Vinagrete',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':12,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':25.0,
                'name':'Ch. c/ Queijo/Vinag.',
                'description':'Contra Filé/Mussarela/Vinagrete',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':13,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':17.0,
                'name':'Mort. c/ Mussarela',
                'description':'Mortadela/Mussarela',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':14,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':14.0,
                'name':'Lanche Natural',
                'description':'Peito de Peru/Mussarela/Alface/Tomate',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':15,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':26.0,
                'name':'X-Tudo',
                'description':'2x Hamurguer/Ovo/Presunto/Calabresa/Bacon/Mussarela/Maionese/Alface/Tomate',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':16,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':20.0,
                'name':'Vasco de Frango',
                'description':'Filé de Frango/Batata Palha/Catupiry/Mussarela',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':17,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':23.0,
                'name':'Vasco de Carne',
                'description':'Contra Filé/Batata Palha/Catupiry/Mussarela',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':18,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':19.0,
                'name':'Vasco de Calabresa',
                'description':'Calabresa/Batata Palha/Catupiry/Mussarela',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':19,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Pão c/ Ovo',
                'description':'Ovo',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':20,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':11.0,
                'name':'Pão c/ Ovo/Mussar.',
                'description':'Ovo/Mussarela/Orégano',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':21,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':14.0,
                'name':'Misto/Batata Palha',
                'description':'Presunto/Batata Palha/Mussarela/Orégano',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':22,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':25.0,
                'name':'Beirute Carne I',
                'description':'Carne/Alface/Tomate/Mussarela/Ovo',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':23,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':28.0,
                'name':'Beirute Carne II',
                'description':'Carne/Alface/Tomate/Mussarela/Ovo/Bacon/Cheddar',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':24,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':24.0,
                'name':'Beirute Frango',
                'description':'Frango/Alface/Tomate/Mussarela/Ovo',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':25,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':22.0,
                'name':'Beirute Calabresa',
                'description':'Calabresa/Alface/Tomate/Mussarela/Ovo',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':26,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Cone Trufado',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':27,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':14.0,
                'name':'Bolo de Pote',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':28,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Brigadeiro',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':29,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':4.0,
                'name':'Sonho de Valsa',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':30,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.0,
                'name':'Barra de Cereais',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':31,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.0,
                'name':'Chocolates',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':32,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':3.0,
                'name':'Paçoquita',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':33,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.0,
                'name':'Trident',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':34,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':5.0,
                'name':'Halls',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':35,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':0.0,
                'name':'Sorvetes',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':36,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':13.0,
                'name':'Salada de Fruta',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':37,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':17.0,
                'name':'Açaí',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':38,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':13.0,
                'name':'Gelatina Colorida',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':39,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':18.0,
                'name':'Copo da Felicidade',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':40,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':15.0,
                'name':'Musse/Chocolate',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':41,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':0.0,
                'name':'Queijo Quente 01',
                'description':'Mussarela/Tomate/Orégano/No Prato',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':42,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':0.0,
                'name':'Queijo Quente 02',
                'description':'Queijo Brancp/Tomate/Orégano/No Prato',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':43,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':0.0,
                'name':'Queijo Quente 03',
                'description':'Queijo Brancp/Tomate Seco/Orégano/No Prato',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':44,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':0.0,
                'name':'Prima',
                'description':'Contra Filé/Bacon/Cheddar/Catupiry/Batata Palha/No Prato',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':45,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Refrigerante Lata',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':46,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Tônica Schweppes',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':47,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Suco Lata',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':48,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'H2O',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':49,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Chá - Lata',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':50,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':15.0,
                'name':'Energético',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':51,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.0,
                'name':'Água c/ Gás',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':52,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':5.0,
                'name':'Água s/ Gás',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':53,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':9.0,
                'name':'Suco de Laranja',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':54,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':11.0,
                'name':'Suco de Melância',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':55,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':11.0,
                'name':'Suco Misto | Polpa',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':56,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.0,
                'name':'Toddynho',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':57,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':11.0,
                'name':'Vitamina Mista',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':58,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':9.0,
                'name':'Gatorade',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':59,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Guaraviton',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':60,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':11.0,
                'name':'Chocolate Batido',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':61,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.5,
                'name':'Café - peq.',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':62,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.5,
                'name':'Café - gde.',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':63,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Capuccino - peq.',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':64,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':9.0,
                'name':'Capuccino - gde.',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':65,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Chocolate - peq.',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':66,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':9.0,
                'name':'Chocolate - gde.',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':67,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':5.0,
                'name':'Chá Quente',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':68,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Pão de Queijo',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':69,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Coxinha',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':70,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Esfihas',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':71,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Folhadinhos',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':72,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':11.0,
                'name':'Quiche',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':73,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':9.0,
                'name':'Empada',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':74,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Bauruzinho',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':75,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Pão de Batata',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':76,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Hamburgão',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':77,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Baguete Folhada',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':78,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Pão na Chapa',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':79,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':11.0,
                'name':'Pão c/ requeijão',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':80,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Mini Pizza',
                'description':'',
                'meal_type':'SNACKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':81,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':24.0,
                'name':'Salada / F. Frango',
                'description':'Filé de Frango - Mussarela/Alface/Tomate/Batata Frita/No Prato',
                'meal_type':'SALADS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':82,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':27.0,
                'name':'Salada / C. Filé',
                'description':'Contra Filé - Mussarela/Alface/Tomate/Batata Frita/No Prato',
                'meal_type':'SALADS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':83,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':21.0,
                'name':'Salada / Calabresa',
                'description':'Calabresa - Mussarela/Alface/Tomate/Batata Frita/No Prato',
                'meal_type':'SALADS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':84,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':10.0,
                'name':'Salada Simples',
                'description':'Alface/Tomate/No Prato',
                'meal_type':'SALADS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':85,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':26.0,
                'name':'Omelete c/ Salada',
                'description':'Ovo/Alface/Tomate/No Prato',
                'meal_type':'SALADS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':86,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':28.0,
                'name':'Lasanha',
                'description':'Massa - Mussarela/Presunto/Molho ao sugo',
                'meal_type':'SALADS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':87,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':14.0,
                'name':'Fritas Pequenas',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':88,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':18.0,
                'name':'Fritas Médias',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':89,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':22.0,
                'name':'Fritas Gde Simples',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':90,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':30.0,
                'name':'Fritas Gde Completa',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':91,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':16.0,
                'name':'calabresa Acebol.',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':92,
                'last_update':1674835337393,
                'restaurant':'Souza de Abreu',
                'prepareTime':20
            },
            {
                'available':True,
                'price':5.0,
                'name':'Água Mineral',
                'description':'Garrafa de água mineral com 500ml',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':0,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.5,
                'name':'Água de Coco',
                'description':'Água de coco de 330ml',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':1,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.5,
                'name':'Café Expresso',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':2,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.5,
                'name':'Café/Leite',
                'description':'Dose média de café ou leite',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':3,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Fell Good Sabores',
                'description':'Lata de chá Fell Good do sabor escolhido com 330ml',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':4,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Chocolate Quente',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':5,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':10.0,
                'name':'RedBull',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':6,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Gatorade',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':7,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':10.0,
                'name':'Vitamina',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':8,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'H20H',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':9,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.5,
                'name':'Ice Tea',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':10,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Bebidas Pilão',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':11,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.5,
                'name':'Refrigerantes',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':12,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':6.5,
                'name':'Sufresh',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':13,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':5.0,
                'name':'Limonada',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':14,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':9.0,
                'name':'Suco Fruta Laranja/Melancia',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':15,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.5,
                'name':'Suco Polpa com Água',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':16,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':10.0,
                'name':'Suco Polpa com Leite',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':17,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':5.0,
                'name':'Toddynho',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':18,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':9.0,
                'name':'Yogurte com Leite',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':19,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':10.0,
                'name':'Yogurte com Polpa e Leite',
                'description':'',
                'meal_type':'DRINKS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':20,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Salgado',
                'description':'',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':21,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':7.0,
                'name':'Pão de Queijo',
                'description':'',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':22,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':9.0,
                'name':'Pão na Chapa',
                'description':'',
                'meal_type':'SANDWICHES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':23,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':18.0,
                'name':'Fritas, Mandioca, Polenta',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':24,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':10.0,
                'name':'Nuggets 4 unid.',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':25,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':14.0,
                'name':'Nuggets 6 unid.',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':26,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':20.0,
                'name':'Nuggets 10 unid.',
                'description':'',
                'meal_type':'PORTIONS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':27,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':30.0,
                'name':'Nhoque ou Talharim',
                'description':'',
                'meal_type':'PASTAS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':28,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':36.0,
                'name':'Rondelli 4 Queijos/Pres. Queijo',
                'description':'',
                'meal_type':'PASTAS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':29,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':36.0,
                'name':'Conchiglione 4 Queijos/Pres. Queijo',
                'description':'',
                'meal_type':'PASTAS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':30,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.0,
                'name':'Massa + 4 Nuggets',
                'description':'',
                'meal_type':'PASTAS',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':31,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':10.0,
                'name':'Palha Italiana',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':32,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.5,
                'name':'Brigadeiro',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':33,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':8.5,
                'name':'Bolos',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':34,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':10.0,
                'name':'Salada de Frutas',
                'description':'',
                'meal_type':'CANDIES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':35,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':29.0,
                'name':'Nuggets 6 unid.',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':36,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':32.0,
                'name':'Omelete (pres, queijo, tomate)',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':37,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':32.0,
                'name':'Calabresa',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':38,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':32.0,
                'name':'Filé de Frango',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':39,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':38.0,
                'name':'Contra Filé',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':40,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':35.0,
                'name':'Parmegiana de Frango',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':41,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':39.0,
                'name':'Parmegiana de Carne',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':42,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':33.0,
                'name':'Strogonoff Frango',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':43,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            },
            {
                'available':True,
                'price':36.0,
                'name':'Strogonoff Carne',
                'description':'',
                'meal_type':'PLATES',
                'photo':'https://avatars.githubusercontent.com/u/30812461?v=4',
                'product_id':44,
                'last_update':1674835337393,
                'restaurant':'Restaurante do H',
                'prepareTime':20
            }
        ],
        'message':'the products were retrieved'
        }
        
        assert viewmodel.to_dict() == expected


