from typing import Dict, List
from src.shared.domain.enums.meal_type_enum import MEAL_TYPE
from src.shared.domain.enums.restaurant_enum import RESTAURANT
from src.shared.domain.repositories.product_repository_interface import IProductRepository
from src.shared.domain.entities.product import Product

class ProductRepositoryMock(IProductRepository):
    products: List[Product]
    
    def __init__(self):
    
        self.products = [
            Product(available=True, price=14.0, name='Lanche Mortadela', description='Mortadela', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=0, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=16.0, name='X-Salada', description='Hamburguer/Mussarela/Maionese/Alface/Tomate', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=1, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='X-Burguer', description='Hamburguer/Mussarela/Maionese', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=2, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=18.0, name='X-Bacon', description='Hamburguer/Bacon/Mussarela/Maionese/Alface/Tomate', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=3, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=15.0, name='X-Egg', description='Hamburguer/Ovo/Mussarela/Maionese/Alface/Tomate', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=4, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=18.0, name='X-Calabresa', description='Calabresa/Mussarela/Alface/Tomate', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=5, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=18.0, name='X-Frango', description='Filé de Frango/Mussarela/Maionese/Alface/Tomate', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=6, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=16.0, name='Americano', description='Presunto/Ovo/Mussarela/Maionese/Alface/Tomate/Orégano', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=7, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=12.0, name='Misto Quente', description='Presunto/Mussarela/Orégano', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=8, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=13.0, name='Bauru', description='Presunto/Mussarela/Tomate/Orégano', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=9, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=18.0, name='Churrasco', description='Contra Filé', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=10, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=21.0, name='Ch. c/ Queijo', description='Contra Filé/Mussarela', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=11, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=23.0, name='Ch. c/ Vinag.', description='Contra Filé/Vinagrete', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=12, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=25.0, name='Ch. c/ Queijo/Vinag.', description='Contra Filé/Mussarela/Vinagrete', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=13, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=17.0, name='Mort. c/ Mussarela', description='Mortadela/Mussarela', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=14, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=14.0, name='Lanche Natural', description='Peito de Peru/Mussarela/Alface/Tomate', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=15, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=26.0, name='X-Tudo', description='2x Hamurguer/Ovo/Presunto/Calabresa/Bacon/Mussarela/Maionese/Alface/Tomate', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=16, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=20.0, name='Vasco de Frango', description='Filé de Frango/Batata Palha/Catupiry/Mussarela', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=17, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=23.0, name='Vasco de Carne', description='Contra Filé/Batata Palha/Catupiry/Mussarela', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=18, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=19.0, name='Vasco de Calabresa', description='Calabresa/Batata Palha/Catupiry/Mussarela', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=19, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='Pão c/ Ovo', description='Ovo', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=20, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=11.0, name='Pão c/ Ovo/Mussar.', description='Ovo/Mussarela/Orégano', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=21, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=14.0, name='Misto/Batata Palha', description='Presunto/Batata Palha/Mussarela/Orégano', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=22, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=25.0, name='Beirute Carne I', description='Carne/Alface/Tomate/Mussarela/Ovo', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=23, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=28.0, name='Beirute Carne II', description='Carne/Alface/Tomate/Mussarela/Ovo/Bacon/Cheddar', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=24, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=24.0, name='Beirute Frango', description='Frango/Alface/Tomate/Mussarela/Ovo', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=25, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=22.0, name='Beirute Calabresa', description='Calabresa/Alface/Tomate/Mussarela/Ovo', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=26, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='Cone Trufado', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=27, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=14.0, name='Bolo de Pote', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=28, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='Brigadeiro', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=29, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=4.0, name='Sonho de Valsa', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=30, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=6.0, name='Barra de Cereais', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=31, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=6.0, name='Chocolates', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=32, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=3.0, name='Paçoquita', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=33, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=6.0, name='Trident', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=34, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=5.0, name='Halls', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=35, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=0.0, name='Sorvetes', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=36, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=13.0, name='Salada de Fruta', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=37, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=17.0, name='Açaí', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=38, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=13.0, name='Gelatina Colorida', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=39, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=18.0, name='Copo da Felicidade', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=40, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=15.0, name='Musse/Chocolate', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=41, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=0.0, name='Queijo Quente 01', description='Mussarela/Tomate/Orégano/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=42, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=0.0, name='Queijo Quente 02', description='Queijo Brancp/Tomate/Orégano/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=43, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=0.0, name='Queijo Quente 03', description='Queijo Brancp/Tomate Seco/Orégano/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=44, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=0.0, name='Prima', description='Contra Filé/Bacon/Cheddar/Catupiry/Batata Palha/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=45, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Refrigerante Lata', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=46, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='Tônica Schweppes', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=47, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='Suco Lata', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=48, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='H2O', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=49, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='Chá - Lata', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=50, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=15.0, name='Energético', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=51, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=6.0, name='Água c/ Gás', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=52, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=5.0, name='Água s/ Gás', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=53, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=9.0, name='Suco de Laranja', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=54, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=11.0, name='Suco de Melância', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=55, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=11.0, name='Suco Misto | Polpa', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=56, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=6.0, name='Toddynho', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=57, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=11.0, name='Vitamina Mista', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=58, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=9.0, name='Gatorade', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=59, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=8.0, name='Guaraviton', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=60, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=11.0, name='Chocolate Batido', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=61, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=6.5, name='Café - peq.', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=62, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.5, name='Café - gde.', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=63, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Capuccino - peq.', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=64, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=9.0, name='Capuccino - gde.', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=65, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Chocolate - peq.', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=66, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=9.0, name='Chocolate - gde.', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=67, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=5.0, name='Chá Quente', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=68, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Pão de Queijo', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=69, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Coxinha', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=70, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Esfihas', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=71, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Folhadinhos', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=72, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=11.0, name='Quiche', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=73, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=9.0, name='Empada', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=74, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Bauruzinho', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=75, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Pão de Batata', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=76, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Hamburgão', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=77, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Baguete Folhada', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=78, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Pão na Chapa', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=79, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=11.0, name='Pão c/ requeijão', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=80, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=7.0, name='Mini Pizza', description='', prepareTime=20, meal_type=MEAL_TYPE.SNACKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=81, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=24.0, name='Salada / F. Frango', description='Filé de Frango - Mussarela/Alface/Tomate/Batata Frita/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SALADS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=82, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=27.0, name='Salada / C. Filé', description='Contra Filé - Mussarela/Alface/Tomate/Batata Frita/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SALADS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=83, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=21.0, name='Salada / Calabresa', description='Calabresa - Mussarela/Alface/Tomate/Batata Frita/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SALADS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=84, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=10.0, name='Salada Simples', description='Alface/Tomate/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SALADS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=85, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=26.0, name='Omelete c/ Salada', description='Ovo/Alface/Tomate/No Prato', prepareTime=20, meal_type=MEAL_TYPE.SALADS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=86, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=28.0, name='Lasanha', description='Massa - Mussarela/Presunto/Molho ao sugo', prepareTime=20, meal_type=MEAL_TYPE.SALADS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=87, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=14.0, name='Fritas Pequenas', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=88, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=18.0, name='Fritas Médias', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=89, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=22.0, name='Fritas Gde Simples', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=90, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=30.0, name='Fritas Gde Completa', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=91, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
            Product(available=True, price=16.0, name='calabresa Acebol.', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=92, last_update=1674835337393, restaurant=RESTAURANT.SOUZA_DE_ABREU),
        
            
            
            Product(available=True, price=5.0, name='Água Mineral', description='Garrafa de água mineral com 500ml', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=0, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=7.5, name='Água de Coco', description='Água de coco de 330ml', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=1, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=6.5, name='Café Expresso', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=2, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=8.5, name='Café/Leite', description='Dose média de café ou leite', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=3, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=7.0, name='Fell Good Sabores', description='Lata de chá Fell Good do sabor escolhido com 330ml', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=4, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=8.0, name='Chocolate Quente', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=5, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=10.0, name='RedBull', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=6, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=8.0, name='Gatorade', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=7, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=10.0, name='Vitamina', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=8, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=7.0, name='H20H', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=9, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=6.5, name='Ice Tea', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=10, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=8.0, name='Bebidas Pilão', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=11, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=6.5, name='Refrigerantes', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=12, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=6.5, name='Sufresh', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=13, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=5.0, name='Limonada', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=14, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=9.0, name='Suco Fruta Laranja/Melancia', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=15, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=7.5, name='Suco Polpa com Água', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=16, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=10.0, name='Suco Polpa com Leite', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=17, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=5.0, name='Toddynho', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=18, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=9.0, name='Yogurte com Leite', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=19, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=10.0, name='Yogurte com Polpa e Leite', description='', prepareTime=20, meal_type=MEAL_TYPE.DRINKS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=20, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=8.0, name='Salgado', description='', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=21, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=7.0, name='Pão de Queijo', description='', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=22, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=9.0, name='Pão na Chapa', description='', prepareTime=20, meal_type=MEAL_TYPE.SANDWICHES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=23, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=18.0, name='Fritas, Mandioca, Polenta', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=24, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=10.0, name='Nuggets 4 unid.', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=25, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=14.0, name='Nuggets 6 unid.', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=26, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=20.0, name='Nuggets 10 unid.', description='', prepareTime=20, meal_type=MEAL_TYPE.PORTIONS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=27, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=30.0, name='Nhoque ou Talharim', description='', prepareTime=20, meal_type=MEAL_TYPE.PASTAS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=28, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=36.0, name='Rondelli 4 Queijos/Pres. Queijo', description='', prepareTime=20, meal_type=MEAL_TYPE.PASTAS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=29, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=36.0, name='Conchiglione 4 Queijos/Pres. Queijo', description='', prepareTime=20, meal_type=MEAL_TYPE.PASTAS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=30, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=8.0, name='Massa + 4 Nuggets', description='', prepareTime=20, meal_type=MEAL_TYPE.PASTAS, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=31, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=10.0, name='Palha Italiana', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=32, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=8.5, name='Brigadeiro', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=33, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=8.5, name='Bolos', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=34, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=10.0, name='Salada de Frutas', description='', prepareTime=20, meal_type=MEAL_TYPE.CANDIES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=35, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=29.0, name='Nuggets 6 unid.', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=36, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=32.0, name='Omelete (pres, queijo, tomate)', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=37, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=32.0, name='Calabresa', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=38, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=32.0, name='Filé de Frango', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=39, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=38.0, name='Contra Filé', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=40, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=35.0, name='Parmegiana de Frango', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=41, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=39.0, name='Parmegiana de Carne', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=42, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=33.0, name='Strogonoff Frango', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=43, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H),
            Product(available=True, price=36.0, name='Strogonoff Carne', description='', prepareTime=20, meal_type=MEAL_TYPE.PLATES, photo='https://avatars.githubusercontent.com/u/30812461?v=4', product_id=44, last_update=1674835337393, restaurant=RESTAURANT.RESTAURANTE_DO_H) 
        ]
    
   
    def get_all_products_group_by_restaurant(self) -> Dict[RESTAURANT, List[Product]]:
        return {restaurant: [product for product in self.products if product.restaurant == restaurant] for restaurant in RESTAURANT}

    def delete_product(self, product_id: int, restaurant: RESTAURANT) -> Product:
        for idx, product in enumerate(self.products):
            if product.restaurant == restaurant and product.product_id == product_id:
                return self.products.pop(idx)
        return None
    
    def create_product(self, product:Product) -> Product:
        self.products.append(product)

        return product

    def get_all_products_by_restaurant(self, restaurant: RESTAURANT) -> List[Product]:
        products = list()
        for product in self.products:
            if product.restaurant == restaurant:
                products.append(product)
        return products
            

        
